Develop 4 tests with different value fields and check toast
pe4enka22/js-hw-assertions pull request #1
Opened 2024-02-01 21:50 UTC by pe4enka22

- create passive of needed values;
- implement before method - redirect to needed page
- develop 4 tests with different field values and check toast design in accordance to field values

2024-02-03 11:00 UTC, DmytroSanitarskyi requested changes

2024-02-03 11:00 UTC, DmytroSanitarskyi commented on cypress/e2e/toastTest.cy.js
> +  toastPosition: 'ng-tns-c209-54',
ці класи можуть змінюватись. В якості орієнтиру, по якому визначати позицію, я би радив пошукати батьківський контейнер тоста і подивитись на його стилі, там явно вказана позиція

2024-02-03 11:00 UTC, DmytroSanitarskyi commented on cypress/e2e/toastTest.cy.js
> +  toastIcon: '<path d=\"M17 9A5 5 0 0 0 7 9a1 1 0 0 0 2 0 3 3 0 1 1 3 3 1 1 0 0 0-1 1v2a1 1 0 0 0 2 0v-1.1A5 5 0 0 0 17 9z"></path>'
Якщо працює, то ок, але я би взяв атрибут котрий ми на занятті обговорювали)

2024-02-03 11:00 UTC, DmytroSanitarskyi commented on cypress/e2e/toastTest.cy.js
> + cy.visit('https://sanitarskyi-ngx-admin.herokuapp.com/');
відформатуйте код, щоб всюди були правильні відступи)

2024-02-03 19:42 UTC, SanitarskyiDmytro requested changes

2024-02-03 19:42 UTC, SanitarskyiDmytro commented on cypress/e2e/toastTest.cy.js
> +    toastPosition: 'static',
Позиція у всіх вийшла однакова, а має бути різною для кожної позиції. Можете спробувати змінити в DevTools значення, щоб впевнитись на 100%, що ви правильно визначили параметр, який відповідає за позицію тоста

2024-02-07 19:57 UTC, DmytroSanitarskyi approved these changes

2024-02-14 14:44 UTC, merged